### ISSUE TITLE
Add the possibility to have two different config for if a window is maximised or not

### ISSUE THREAD

**Issue by charlesmilette** [Elestriel/TaskbarTools#1]
For example I'd like to have it blurred when one of my window is maximised, and transparent when not.

**Comment by Elestriel** [comment]
I'll be working on this soon. It's a little tricky, since I have to figure out which desktop a window is maximized in, and then change the settings of that desktop's taskbar.

**Comment by olliethepikachu** [comment]
I've been looking into this on my TranslucentTb fork, and haven't found a way to distinguish `Shell_SecondaryTrayWnd` taskbars. I ended up implementing it but with all task bars.

**Comment by Elestriel** [comment]
I'd love to check out what you've done. I have an idea for distinguishing taskbars, but I'd have to sit down and try it. Unfortunately I'm not home right now :(

**Comment by olliethepikachu** [comment]
[If you didn't find the repo](https://github.com/olliethepikachu/TranslucentTB)

**Comment by olliethepikachu** [comment]
Using `MonitorFromWindow` it's possible to get the monitor any HWND is in. It also looks like making a `MONITORINFOEX` and using `GetMonitorInfo` can, with the `szDevice` variable, retrieve the display name, like `\\.\DISPLAY1`. Then you'd have to remove the first 11 (I think) letters of the result, and you'd get the display number. A bit hacky, and currently I can't test it, but it should work.

**Comment by Elestriel** [comment]
I took what you said and ran with it. I've got it working pretty much perfectly, now, but I'm making some other HUGE changes to the code in terms of the way settings are saved, and in the general layout of the code. I'm making it more Object-Oriented and cleaning up a ton of messy code. I'll have a release out tomorrow. Going to see Star Wars tonight!

**Comment by olliethepikachu** [comment]
Nice. Tell me how Rogue One is after you see it XD

**Comment by Elestriel** [comment]
Resolved in 1.0.7
