### ISSUE TITLE
Closing a Maximized window doesn't update the taskbar. 

### ISSUE THREAD

**Issue by Elestriel** [Elestriel/TaskbarTools#13]
See if there's a message to catch in this case.

**Comment by Elestriel** [comment]
Fixed in 1.0.8.

**Comment by Droyk** [comment]
Hey what happened @Elestriel did you stop developing TaskbarTools anymore?

**Comment by Elestriel** [comment]
I'm in Japan :p

**Comment by Droyk** [comment]
Hey that's really good, hope you are having a really good time there and you should totally enjoy your time.
I don't want to ask this when you are having a good time but will you gonna work on the feature users suggested or will it take time or are you going to work on them soon.

Don't worry it's completely okay if you don't want to work on this project anymore.

**Comment by Elestriel** [comment]
I do want to work on it but I'm going to be very busy. When I get back I'm
going to a few different states for work.

People are, of course, invited to help out. If you have any programming
knowledge, feel free to contribute!

**Comment by Droyk** [comment]
okay.
