### ISSUE TITLE
Set to Minimise Breaks App!

### ISSUE THREAD

**Issue by DjCrqss** [Elestriel/TaskbarTools#20]
In the options menu on the app, there is a button that says open minimised or something along those lines... I turned it on to see if it would help with another bug but now whenever I open the exe the app closes and hides but still runs in the background. What do I do?

**Comment by wopian** [comment]
Thats the expected behaviour of `Start Minimized`

Double click its icon in your taskbar to open the application

**Comment by DjCrqss** [comment]
Ohh, thanks wopain! It just closed and the icon wasn't on the taskbar, it was in the arrow so I didn't think of looking there. Cheers
