### ISSUE TITLE
Detected as malware by Windows Defender

### ISSUE THREAD

**Issue by wopian** [Elestriel/TaskbarTools#21]
Version: 1.0.8

Running the application normally is all fine, however when the option to start with Windows is toggled on, Windows Defender detects it as the following:

```plain
Detected Item: Trojan:Win32/Rundas.A

Alert Level: Severe

Category: Trojan

Description: This program is dangerous and executes commands from an attacker.

Recommended action: Remove this software immediately.

Items: 
file:C:\Users\wopia\Downloads\Taskbar\TaskbarTool.exe
runkey:HKCU@S-1-5-21-2514878431-4172358072-2079176248-1002\SOFTWARE\MICROSOFT\WINDOWS\CURRENTVERSION\RUN\\TaskbarTools
regkey:HKCU@S-1-5-21-2514878431-4172358072-2079176248-1002\SOFTWARE\MICROSOFT\WINDOWS\CURRENTVERSION\RUN\\TaskbarTools

```

**Comment by Aemony** [comment]
For some reason compiling to AnyCPU and x86 triggers a couple of false positives. x64, however, does not do this.

VirusTotal:
* [AnyCPU](https://virustotal.com/en/file/849102966cf5e54b02b3478fabe174302accc7d6b4002236116a7a6b55969e7b/analysis/1487078404/)
* [x86](https://virustotal.com/en/file/41289767f6812eb042366e7f7da7a7e5926da41542f50dc48295abc3d3a64048/analysis/1487078418/)
* [x64](https://virustotal.com/en/file/4e4734bea48868ff6d129bd2325fd7fd5d46f3938a8688e139a4e143cb77c2fb/analysis/1487078427/)

I've compiled a x64 version of the application which you can download if you'd like from this link:
[TaskbarTool 1.0.8.0 x64.zip](https://github.com/Elestriel/TaskbarTools/files/774165/TaskbarTool.1.0.8.0.x64.zip). It should work just the same on x64 versions of Windows.
